import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { CountUp } from "../lib";
/* ============================================================
   Slide 1 — Opening
   ============================================================ */
function Slide1({ active }) {
    return (_jsxs("div", { className: "s1 " + (active ? "s1--enter" : ""), children: [_jsxs("div", { className: "s1__left", children: [_jsxs("div", { children: [_jsxs("div", { className: "s1__eyebrow", children: [_jsx("span", { className: "dot" }), _jsx("span", { children: "Investor Presentation \u00B7 March 2026" })] }), _jsxs("h1", { className: "s1__title", children: ["Asia Investor", _jsx("br", {}), "Meetings", _jsx("br", {}), _jsx("em", { children: "Non-Deal Roadshow" })] })] }), _jsxs("div", { className: "s1__bottom", children: [_jsx("span", {}), _jsx("span", { children: "Tokyo \u00B7 Singapore \u00B7 Hong Kong" })] })] }), _jsxs("div", { className: "s1__right", children: [_jsx("div", { className: "s1__grid" }), _jsx("div", { className: "s1__compass", children: _jsx("div", { className: "s1__star-big", children: _jsx("span", { className: "s1__logo-mark", "aria-hidden": "true" }) }) }), _jsxs("div", { className: "s1__stat-card tl", children: [_jsxs("div", { className: "num", children: [_jsx(CountUp, { to: 5, play: active }), "\u00A0", _jsx("span", { style: { color: "var(--ink-3)", fontWeight: 400, fontSize: 18 }, children: "members" })] }), _jsx("div", { className: "label", children: "Sovereign shareholders" })] }), _jsxs("div", { className: "s1__stat-card mid", children: [_jsxs("div", { className: "num accent", children: ["A+ ", _jsx("span", { style: { color: "var(--ink-3)", fontWeight: 400, fontSize: 18 }, children: "/" }), " A2"] }), _jsx("div", { className: "label", children: "S&P \u00B7 Moody\u2019s \u00B7 Stable" })] }), _jsxs("div", { className: "s1__stat-card br", children: [_jsxs("div", { className: "num", children: ["USD ", _jsx(CountUp, { to: 2.6, decimals: 1, play: active }), "bn"] }), _jsx("div", { className: "label", children: "Gross loan portfolio" })] }), _jsxs("div", { className: "s1__flags", children: [_jsxs("div", { className: "s1__flag", children: [_jsx("span", { className: "s1__flag-emoji", children: "\uD83C\uDDE6\uD83C\uDDF7" }), _jsx("span", { children: "AR" })] }), _jsxs("div", { className: "s1__flag", children: [_jsx("span", { className: "s1__flag-emoji", children: "\uD83C\uDDE7\uD83C\uDDF4" }), _jsx("span", { children: "BO" })] }), _jsxs("div", { className: "s1__flag", children: [_jsx("span", { className: "s1__flag-emoji", children: "\uD83C\uDDE7\uD83C\uDDF7" }), _jsx("span", { children: "BR" })] }), _jsxs("div", { className: "s1__flag", children: [_jsx("span", { className: "s1__flag-emoji", children: "\uD83C\uDDF5\uD83C\uDDFE" }), _jsx("span", { children: "PY" })] }), _jsxs("div", { className: "s1__flag", children: [_jsx("span", { className: "s1__flag-emoji", children: "\uD83C\uDDFA\uD83C\uDDFE" }), _jsx("span", { children: "UY" })] })] })] })] }));
}
export default Slide1;
