import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/* ============================================================
   Slide 34 — Closing card · logo + contact
   ============================================================ */
import { StarMark } from "../lib";
function Slide34() {
    return (_jsxs("div", { className: "s34", children: [_jsxs("svg", { className: "s34__bg", viewBox: "0 0 1600 900", preserveAspectRatio: "xMidYMid slice", children: [_jsxs("defs", { children: [_jsxs("linearGradient", { id: "s34-sky", x1: "0", x2: "0", y1: "0", y2: "1", children: [_jsx("stop", { offset: "0%", stopColor: "var(--paper-2)" }), _jsx("stop", { offset: "60%", stopColor: "var(--paper)" }), _jsx("stop", { offset: "100%", stopColor: "var(--accent-soft)" })] }), _jsx("pattern", { id: "s34-grid", width: "40", height: "40", patternUnits: "userSpaceOnUse", children: _jsx("path", { d: "M 40 0 L 0 0 0 40", fill: "none", stroke: "var(--rule)", strokeWidth: "0.5" }) })] }), _jsx("rect", { width: "1600", height: "900", fill: "url(#s34-sky)" }), _jsx("rect", { width: "1600", height: "900", fill: "url(#s34-grid)", opacity: "0.4" }), _jsxs("g", { transform: "translate(0,640)", opacity: "0.5", children: [[60, 140, 200, 260, 330, 420, 500, 560, 640, 720, 820, 900, 980, 1060, 1140, 1220, 1320, 1420, 1500].map((x, i) => {
                                const h = 40 + ((i * 17) % 80);
                                const w = 32 + (i % 3) * 8;
                                return _jsx("rect", { x: x, y: -h, width: w, height: h, fill: "var(--accent)", opacity: "0.18" }, i);
                            }), _jsx("line", { x1: "0", y1: "0", x2: "1600", y2: "0", stroke: "var(--accent)", strokeOpacity: "0.3", strokeWidth: "1" })] }), [200, 460, 800, 1180, 1440].map((x, i) => (_jsxs("g", { transform: `translate(${x},520)`, opacity: "0.55", children: [_jsx("line", { x1: "0", y1: "0", x2: "0", y2: "180", stroke: "var(--ink-3)", strokeWidth: "1.5" }), _jsx("circle", { cx: "0", cy: "0", r: "6", fill: "none", stroke: "var(--ink-3)", strokeWidth: "1.5" }), _jsx("circle", { cx: "0", cy: "0", r: "3", fill: "var(--accent)", opacity: "0.6" })] }, i)))] }), _jsxs("div", { className: "s34__panel", children: [_jsxs("div", { className: "s34__brand", children: [_jsx("span", { className: "s34__star", children: _jsx(StarMark, { size: 76 }) }), _jsx("div", { className: "s34__wordmark", children: "FONPLATA" }), _jsx("div", { className: "s34__sub", children: "Development Bank" })] }), _jsx("div", { className: "s34__rule" }), _jsx("div", { className: "s34__tagline", children: "Connecting people. Funding regions." }), _jsxs("div", { className: "s34__contacts", children: [_jsxs("a", { className: "s34__contact", href: "mailto:contacto@fonplata.org", children: [_jsx("span", { className: "s34__contact-icon", children: _jsxs("svg", { viewBox: "0 0 24 24", width: "22", height: "22", children: [_jsx("rect", { x: "3", y: "6", width: "18", height: "13", rx: "1.5", fill: "none", stroke: "currentColor", strokeWidth: "1.5" }), _jsx("path", { d: "M 3 7 L 12 13 L 21 7", fill: "none", stroke: "currentColor", strokeWidth: "1.5" })] }) }), _jsxs("div", { children: [_jsx("div", { className: "s34__contact-eye", children: "Email" }), _jsx("div", { className: "s34__contact-val", children: "contacto@fonplata.org" })] })] }), _jsxs("a", { className: "s34__contact", href: "https://www.fonplata.org", target: "_blank", rel: "noreferrer", children: [_jsx("span", { className: "s34__contact-icon", children: _jsxs("svg", { viewBox: "0 0 24 24", width: "22", height: "22", children: [_jsx("circle", { cx: "12", cy: "12", r: "9", fill: "none", stroke: "currentColor", strokeWidth: "1.5" }), _jsx("ellipse", { cx: "12", cy: "12", rx: "9", ry: "3.5", fill: "none", stroke: "currentColor", strokeWidth: "1.2" }), _jsx("line", { x1: "3", y1: "12", x2: "21", y2: "12", stroke: "currentColor", strokeWidth: "1.2" }), _jsx("line", { x1: "12", y1: "3", x2: "12", y2: "21", stroke: "currentColor", strokeWidth: "1.2" })] }) }), _jsxs("div", { children: [_jsx("div", { className: "s34__contact-eye", children: "Website" }), _jsx("div", { className: "s34__contact-val", children: "www.fonplata.org" })] })] })] }), _jsx("div", { className: "s34__rule" }), _jsxs("div", { className: "s34__meta", children: [_jsx("span", { children: "Investor Relations" }), _jsx("span", { children: "\u00B7" }), _jsx("span", { children: "Asia NDR \u00B7 March 2026" })] })] })] }));
}
export default Slide34;
